packages:
  - .tests
  - default
  - node-custom-server
  - unstable_rsc-data-mode-vite
  - unstable_rsc-framework-mode

allowBuilds:
  esbuild: false
  sharp: false
  workerd: false

minimumReleaseAge: 10800
minimumReleaseAgeExclude:
  - react-router
  - "@react-router/*"
